image: docker
services:
  - docker:dind
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
